name: Build and Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.101'
        
    - name: Restore dependencies
      run: |
        cd Imc && dotnet restore

    - name: Build project
      run: | 
          cd Imc && dotnet publish --configuration Release -o ../dist /p:PublishSingleFile=false /p:PublishTrimmed=true

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Imc/dist